name: amazon_clone
description: amazon-clone project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  linkwell: ^2.0.6
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  rating_dialog: ^2.0.4
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
# assets
  assets:
    - assets/
    - assets/images/
    - assets/categoryLogos/
    - assets/largeAds/
    - assets/smallAds/

  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
